services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: cheking_file_web
    restart: always
    ports:
      - "3000:80"
    #depends_on:
    #  - backend