version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: checking_files_db
    restart: always
    environment:
      POSTGRES_DB: checking_files_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d checking_files_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: cheking_file_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: cheking_file_web
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: