# Generated by Django 6.0.6 on 2026-06-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("extension", models.CharField(max_length=10)),
                ("size", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
                ("is_safe", models.BooleanField()),
                ("risk_level", models.CharField(max_length=10)),
                ("details", models.JSONField()),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="checker.file",
                    ),
                ),
            ],
        ),
    ]
